###

GET http://localhost:3000/items/getAll
sessionid: 1111
cuid: system

###

GET http://localhost:3000/items/findById/620cbeaecc90432d95b598a0
sessionid: 1111
cuid: system

###

POST http://localhost:3000/items/findByLabel
Content-Type: application/json
sessionid: 1111

{
 "labelIds": ["61b36e2d87d9a8ebbd1c184f"]
}

###

POST http://localhost:3000/items/create
Content-Type: application/json
sessionid: 1111

{
    "name": {
      "en": "board",
      "de": "Brett"
    },
    "description": {
      "en": "Boarddescription",
      "de": "Brettbeschreibung"
    },
    "countable": false,
    "labelIds": ["61b36e2d87d9a8ebbd1c184f"]
}


#### Example with shiningId.

POST http://localhost:3000/items/create
Content-Type: application/json
sessionid: 1111

{
    "name": {
      "en": "Screw",
      "de": "Schraube"
    },
    "description": {
      "en": "Boarddescription",
      "de": "Brettbeschreibung"
    },
    "countable": false,
    "labelIds": ["61e7c4f6f676f994a67e0244","61e809abc23c98bb9551e761"]
}

###

DELETE http://localhost:3000/items/delete/620cbeaecc90432d95b598a6
Content-Type: application/json
sessionid: 1111
cuid: system
