
POST http://localhost:3000/light/turnOn
Content-Type: application/json
sessionid: 1111
cuid: system

{
  "itemId": "620b7837fe2394f0e1a84e89",
  "duration": 8,
  "color": "#2a33FF"
}

###

POST http://localhost:3000/light/turnOff
sessionid: 1111
Content-Type: application/json
cuid: system

{
  "itemId": "620b7837fe2394f0e1a84e89",
  "color": "#111111"
}

###
