###

POST http://localhost:3000/shelves/create
Content-Type: application/json

{
  "number": 3,
  "roomId": "61e98d7a2d3bf61c3f4d1e7e"
}
###

GET http://localhost:3000/shelves/getAll
###

GET http://localhost:3000/shelves/findById/620e55ad6f7dfecedf0611c9
###

POST http://localhost:3000/shelves/update/620e43c1446d42e77a578f6e
Content-Type: application/json

{
  "number": 6,
  "roomID": "620e43c1446d42e77a578f66"
}
###

DELETE http://localhost:3000/shelves/delete/620e6528a90dbfd52fbcf884
Content-Type: application/json
###

